import {Lato } from "next/font/google";
import "./globals.css";

const Loto = Lato({ subsets: ["latin"] });

export const metadata = {
  title: "BookPartyPlace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Loto.className}>{children}</body>
    </html>
  );
}
