import { Lato } from "next/font/google";
import "./globals.css";
import Providers from "@/redux/Providers";

const Loto = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
  title: "BookPartyPlace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="container mx-auto" lang="en">
      <body className={Loto.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
